on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
name: Build Packages
jobs:
  flatpak:
    name: Flatpak Build
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: Redot.flatpak
        manifest-path: org.redotengine.Redot.yaml
        cache-key: flatpak-builder-${{ github.sha }}
  snap:
    name: Snapcraft Build
    runs-on: ubuntu-latest

    steps:

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      - name: Install LXD
        uses: canonical/setup-lxd@main

      - name: Snapcraft Build
        run: snapcraft

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Redot.snap
          path: redot*.snap

